repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        exclude: migrations/.*
        require_serial: true
        language: python
        types_or: [cython, pyi, python]

  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black
        language: system
        exclude: 'migrations/.*|tasks.py'
        types:
          - python

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8 --config setup.cfg
        language: system
        stages:
          - pre-commit
          - pre-push
        types:
          - python

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check --force-exclude
        language: system
        stages:
          - pre-commit
          - pre-push
        types:
          - python
