version: '3'
services:
  api:
    build: .
    network_mode: host
    restart: always
    env_file:
      - .env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
