version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - fastapi-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - fastapi-net

networks:
  fastapi-net:
